version: 2.1

workflows:
  build-deploy:
    jobs:
      - build:
        filters:
          tags:
            only: /.*/ 
      - publish-docker:
          requires:
            - build
          filters:
            tags:
              only: /.*/

working_directory: &working_directory
                     ~/repo

jobs:
  build:
    docker:
      - image: circleci/node:12.13.0

    working_directory: *working_directory

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install --production

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: *working_directory
          paths:
            - node_modules

  publish-docker:
    working_directory: *working_directory
    docker:
      - image: docker:18.06.0-ce-git
    steps:
      - attach_workspace:
          at: *working_directory
      - setup_remote_docker:
          docker_layer_caching: true 
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=awconstable/dashboard-leankit-metric-extractor -t awconstable/dashboard-leankit-metric-extractor:0-SNAPSHOT .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar awconstable/dashboard-leankit-metric-extractor
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS 
            docker push awconstable/dashboard-leankit-metric-extractor:0-SNAPSHOT
            
            if [ -n "$CIRCLE_TAG" ]; then
              docker tag awconstable/dashboard-leankit-metric-extractor:0-SNAPSHOT awconstable/dashboard-leankit-metric-extractor:latest
              docker tag awconstable/dashboard-leankit-metric-extractor:0-SNAPSHOT awconstable/dashboard-leankit-metric-extractor:$CIRCLE_TAG
              docker push awconstable/dashboard-leankit-metric-extractor:latest
              docker push awconstable/dashboard-leankit-metric-extractor:$CIRCLE_TAG
            fi